import { test, expect } from '@playwright/test';

/**
 * E2E checkout flow.
 * Checkout is currently a simulated payment (alert + clearCart()).
 */

test('checkout: pagar ahora -> muestra alerta y vacía el carrito', async ({ page }) => {
  await page.goto('/productos');
  await page.getByRole('button', { name: /añadir al carrito/i }).first().click();

  await page.goto('/checkout');
  await expect(page.getByRole('heading', { name: /contacto/i })).toBeVisible();

  // Capture the alert generated by handlePago()
  let dialogText = '';
  page.on('dialog', async (dialog) => {
    dialogText = dialog.message();
    await dialog.accept();
  });

  await page.getByRole('button', { name: /pagar ahora/i }).click();

  await expect.poll(() => dialogText).toMatch(/Simulación de pago/i);

  // After paying, checkout summary should show empty cart message
  await expect(page.getByText(/Tu carrito está vacío/i)).toBeVisible();

  // And localStorage cart should be removed
  const cart = await page.evaluate(() => localStorage.getItem('cart'));
  expect(cart).toBeNull();
});
